---
title: 'ESM 262: Assignment 2'
author: "Laura Ingulsrud and Keene Morrow"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

##Input to Function:

###1. Table with prices for different fish
```{r fishprice}

# Create different fish (Pokemon)
fish = c("Magikarp", "Goldeen", "Seaking", "Horsea", "Seadra")

# Create prices for fish
prices = c(10, 12, 16, 20, 25)

# Create table with prices and fish
fish_prices <- data.frame(row.names = fish, prices)
fish_prices

```


###2. Table with number caught for each fish species for each location
```{r catchlocation}

# Create locations where each fish species is caught
locations = c("Vermilion City", "Cerulean City", "Pallet Town", "Pewter City", "Cinnabar Island")

# Create catch number for each location
Vermilion = c(500, 350, 290, 50, 160)
Cerulean = c(200, 430, 300, 120, 230)
Pallet = c(320, 120, 320, 35, 130)
Pewter = c(480, 190, 140, 15, 220)
Cinnabar = c(150, 400, 220, 70, 90)

catch_location = c(Vermilion, Cerulean, Pallet, Pewter, Cinnabar)

# Create table with catch at each location
fish_catch <- matrix(c(catch_location), 
                     nrow = 5, ncol = 5,
                     dimnames = list(c(fish), c(locations)))
fish_catch

```

##Function:
```{r function}

# Bring in fisheries simulation function
source("fisheries_simulation.R")

```

##Run function:
```{r run}

# Run function
fisheries_simulation(fish_catch, fish_prices, plot = T)

```
